<a href="https://colab.research.google.com/github/SBR2006V/Google-Colab/blob/main/1_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [8]:
numbers = input("Enter number seperated by spaces: ")
arr = np.array([int(x) for x in numbers.split()])
print("Array:", arr)
print("Data Type:", arr.dtype)
print("Shape:", arr.shape)
print("Size:", arr.size)

Enter number seperated by spaces: 10 20 30 40 50
Array: [10 20 30 40 50]
Data Type: int64
Shape: (5,)
Size: 5


In [9]:
marks = np.array([
 [85, 90, 78],
 [75, 88, 92],
 [90, 85, 89],
 [70, 80, 75],
 [95, 92, 96]
])
print("Marks of 5 Students:")
print(marks)
print("Dimensions:", marks.ndim)
print("Shape:", marks.shape)

Marks of 5 Students:
[[85 90 78]
 [75 88 92]
 [90 85 89]
 [70 80 75]
 [95 92 96]]
Dimensions: 2
Shape: (5, 3)


In [10]:
print("Array using arange():")
print(np.arange(1, 11))
print("\nArray using linspace():")
print(np.linspace(0, 1, 5))
print("\nZero Matrix:")
print(np.zeros((3, 3), dtype=int))
print("\nOnes Matrix:")
print(np.ones((3, 3), dtype=int))
print("\nIdentity Matrix:")
print(np.eye(3, dtype=int))

Array using arange():
[ 1  2  3  4  5  6  7  8  9 10]

Array using linspace():
[0.   0.25 0.5  0.75 1.  ]

Zero Matrix:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Ones Matrix:
[[1 1 1]
 [1 1 1]
 [1 1 1]]

Identity Matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [11]:
a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [12 24 35 48]
Subtraction: [ 8 16 25 32]
Multiplication: [ 20  80 150 320]
Division: [5. 5. 6. 5.]


In [12]:
A = np.array([
 [1, 2],
 [3, 4]
])
B = np.array([
 [5, 6],
 [7, 8]
])
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nMatrix Multiplication:")
print(np.matmul(A, B))

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Matrix Multiplication:
[[19 22]
 [43 50]]
