<a href="https://colab.research.google.com/github/SBR2006V/Google-Colab/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
a = np.array ([10, 20, 30, 40])
print(a)

[10 20 30 40]


In [10]:
a = np.array ([10, 20, 30, 40])
b = (a + 5)
print(b)

[15 25 35 45]


In [11]:
a = np.array ([10, 20, 30, 40])
b = (a - 2)
print(b)

[ 8 18 28 38]


In [22]:
a = np.array ([10, 20, 30, 40])
b = (a / 5)
print(b)

[2. 4. 6. 8.]


In [20]:
a = np.array ([10, 20, 30, 40])
b = (a * 3)
print(b)

[ 30  60  90 120]


In [25]:
a = np.array ([10, 20, 30, 40])
print(np.max(a))

40


In [26]:
a = np.array ([10, 20, 30, 40])
print(np.min(a))

10


In [27]:
a = np.array ([10, 20, 30, 40])
print(np.sum(a))

100


In [28]:
a = np.array ([10, 20, 30, 40])
print(np.average(a))

25.0


In [31]:
a = np.array ([2, 3, 4, 5, 6, 7, 8, 11])
even = a[a % 2 == 0]
odd = a[a % 2 != 0]
print(even)
print(odd)

[2 4 6 8]
[ 3  5  7 11]
